version: "3"

services:
  server:
    build: ./
    ports:
      - '${LOCAL_PORT}:${CONTAINER_PORT}'
    depends_on:
      - database
  database:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '${DB_LOCAL_PORT}:${DB_CONTAINER_PORT}'
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_APP}'
volumes:
    db-data: