version: "3"

services:
  server:
    build: build/
    ports:
      - '${LOCAL_PORT}:${CONTAINER_PORT}'
    depends_on:
      - database
  database:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '${DB_LOCAL_PORT}:${DB_CONTAINER_PORT}'- "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
volumes:
    db-data: